# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "evolutionsim"
BBFILE_PATTERN_evolutionsim = "^${LAYERDIR}/"
BBFILE_PRIORITY_evolutionsim = "10"

# This should only be incremented on significant changes that will
# cause compatibility issues with other layers
LAYERVERSION_evolutionsim = "1"

LAYERDEPENDS_evolutionsim = "core"

LAYERSERIES_COMPAT_evolutionsim = "scarthgap"
